# Generated by Django 3.0.4 on 2020-06-22 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('qrcode_image', models.ImageField(upload_to='qrcode/')),
                ('qrcode_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_subinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameC', models.CharField(max_length=30, null=True)),
                ('resident_registration_number', models.CharField(max_length=30)),
                ('driver_license', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
