# Generated by Django 3.0.4 on 2020-06-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user', models.CharField(max_length=30)),
                ('request_user', models.CharField(max_length=30)),
            ],
        ),
    ]
