# Generated by Django 3.0.4 on 2020-05-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20200501_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_subinfo',
            name='usernameC',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
