# Generated by Django 3.0.4 on 2020-05-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20200501_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('qrcode_image', models.ImageField(upload_to='qrcode/')),
                ('qrcode_id', models.CharField(max_length=10)),
            ],
        ),
    ]
