# Generated by Django 3.0.4 on 2020-05-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_qrcode_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode_info',
            name='qrcode_id',
            field=models.CharField(max_length=20),
        ),
    ]
