# Generated by Django 3.0.4 on 2020-05-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_auto_20200514_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode_info',
            old_name='image',
            new_name='qrcode_image',
        ),
    ]
