# Generated by Django 3.0.4 on 2020-05-16 23:00

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_auto_20200515_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_subinfo',
            name='face_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/'),
        ),
    ]
