# Generated by Django 3.0.4 on 2020-05-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_auto_20200516_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_subinfo',
            name='face_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
