# Generated by Django 3.0.4 on 2020-05-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_auto_20200516_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_subinfo',
            name='face_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
